version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      front_net:

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
      front_net:
        aliases:
          - post

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      front_net:
      back_net:

  node-exporter:
    image: prom/node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:
      back_net:

  mongodb-exporter:
    image: ${USER_NAME}/mongodb_exporter
    environment:
      MONGODB_URL: 'mongodb://post_db:27017'
    networks:
      front_net:
      back_net:

  blackbox-exporter:
    image: ${USER_NAME}/blackbox_exporter
    networks:
      front_net:
      back_net:

volumes:
  post_db:

networks:
  front_net:
  back_net:
