rm admin.csr
rm admin-csr.json
rm admin-key.pem
rm admin.pem
rm ca-config.json
rm ca.csr
rm ca-csr.json
rm ca-key.pem
rm ca.pem
rm kube-proxy.csr
rm kube-proxy-csr.json
rm kube-proxy-key.pem
rm kube-proxy.pem
rm kubernetes.csr
rm kubernetes-csr.json
rm kubernetes-key.pem
rm kubernetes.pem
rm worker-0.csr
rm worker-0-csr.json
rm worker-0-key.pem
rm worker-0.pem
rm worker-1.csr
rm worker-1-csr.json
rm worker-1-key.pem
rm worker-1.pem
rm worker-2.csr
rm worker-2-csr.json
rm worker-2-key.pem
rm worker-2.pem
